name: GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

env:
    PCDPASS_URL: "https://zupass.org"

jobs:
    deploy:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install dependencies
              run: yarn

            - name: Build
              run: yarn build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./apps/client/dist
                  cname: pcd-issuer.cedoor.dev
